#spring.application.name=springboot-1
#
#spring.datasource.url=jdbc:mysql://localhost:3306/mydb
#spring.datasource.username=root
#spring.datasource.password=tinu
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#server.port=8080

# =============================================
# DATABASE - Railway MySQL
# =============================================
spring.datasource.url=jdbc:mysql://thomas.proxy.rlwy.net:17628/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=YLisDOtrgfUWiBnKLKIxtyhVRhZhFLZE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =============================================
# JPA / HIBERNATE
# =============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# =============================================
# SERVER
# =============================================
server.port=8080